language: c++

compiler: clang

before_install:
  - pip install --user cpp-coveralls

install:
  
script: 
  - mkdir target
  - make test debug_var=2

after_success:
  - coveralls --exclude mylib --exclude test --gcov-options '\-lp'
