language: c++

#compiler: clang

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install cmake

install:
  
script: 
  - mkdir target
  - bash script/env-search.sh 
  - cat .factor
  - make test debug_var=2

after_success:
  - coveralls --exclude mylib --exclude test --gcov-options '\-lp'
