language: c++

compiler: clang

before_install:
  - pip install --user cpp-coveralls
  - git clone https://github.com/google/googletest.git && cd googletest/googletest && g++ -isystem ./include -I./ -pthread -c ./src/gtest-all.cc && ar -rv libgtest.a gtest-all.o

install:
  
script: 
  - ls
  - ls googletest
  - ls googletest/googletest
  - cp googletest/googletest/libgtest.o test/
  - mkdir target
  - make test

after_success:
  - coveralls --exclude mylib --exclude test --gcov-options '\-lp'
